Month8/step2
Sobolefff/react-burger pull request #4
Opened 2022-09-14 18:04 UTC by Sobolefff

2022-09-14 21:12 UTC, randomroot requested changes
Доброго времени суток!

Вами была проделана большая работа, основная функциональность по переносу значений в redux и взаимодействию с ним была реализована, все необходимые `actions` были добавлены. Отдельно хотелось бы отметить самостоятельную реализацию автоматического и ручного переключения в навигации по ингредиентам.

Однако, для успешной сдачи работы вам необходимо исправить недостатки, согласно комментариям к ревью и обратить внимание на предложения по улучшению вашего кода, для повышения его качества, читабельности и производительности. Среди прочего хотелось бы обратить ваше внимание на следующие моменты:

1) Отсутствует отступ между заголовком "Соберите бургер" и хедером;
2) `Actions` и `reducers` у вас находятся каждый в едином файле для всего приложения в целом. Рекомендую разделить их на отдельные, каждый из которых будет относится к той или иной сущности/компоненте, что упростит их визуальное восприятие (большой объем кода в файле непросто тестировать и оценивать качество), а кроме того улучшит архитектурную составляющую вашего приложения и позволит разделить большой `state` на более мелкие, каждому из которых можно будет прописать своё начальное значение и избежать случайных ошибок.
3) Логика подсчета счетчиков выбранных ингредиентов выглядит немного запутанно и не оптимальна по реализации, попробуйте найти альтернативный подход подсчета, чтобы уменьшить издержки по их вычислению;

2022-09-14 21:12 UTC, randomroot commented on src/components/app/app.jsx
> +  const oneFetch = useRef(false);
🟡 **Можно улучшить:**

В целом проверять на повторную проверку необязательно, метод `dispatch` с большой вероятностью не изменится во время работы приложения, поэтому `useEffect` отработает всего один раз при старте

2022-09-14 21:12 UTC, randomroot commented on src/components/app/app.jsx
> +    return () => (oneFetch.current = true);
🟡 **Можно улучшить:**

В данном случае лучше использовать фигурные скобки, так как нет возвращаемого значения, которое обычно оборачивается в круглые

2022-09-14 21:12 UTC, randomroot commented on src/components/app/app.jsx
> +export const store = createStore(rootReducer, enhancer);
🟡 **Можно улучшить:**

Переменную `store` и её инициализацию лучше вынести в отдельный файл в папке `services`, чтобы отделить логику создания и хранения стора от конкретного компонента (App)

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
>  //import { ArrayPropTypes } from "../../utils/proptypes";
🟡 **Можно улучшить:**

Неиспользуемые импорты можно безопасно удалить из кода

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +  // useEffect(() => {
🔴 **Нужно исправить:**

Неиспользуемый или закомментированный код следует удалять из файла, при необходимости его можно будет восстановить через историю в Git

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    let totalPrice = bun && bunsPrice
🔴 **Нужно исправить:**

Данная переменная не изменяется далее в коде, поэтому её следует сделать константой

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +      ? filling.reduce(function(acc, obj) {
🔴 **Нужно исправить:**

Варианты вызова двух функций отличаются только начальным значением, следует убрать дублирование кода и перенести нужно проверку непосредственно в параметр начального значения

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
>      setIsOrderDetailsOpened(true);
🟡 **Можно улучшить:**

Открывать модальное окно с результатом заказа целесообразно только в случае, если удалось успешно выполнить запрос на сервер, в противном случае окно останется пустым

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +  const orderData = bun && filling && Array.from(filling.map((el) => el._id)).concat(bunIdArr);
🔴 **Нужно исправить:**

1) Линии кода, отвечающие за подготовку массива ID-шников для запроса, следует перенести непосредственно в метод, где происходит обращение к API, т.к. данные значения используются только в методе `openModal` и вычислять их при каждом рендере нецелесообразно;

2) Функция `map` возвращает в качестве результата массив, поэтому нет необходимости оборачивать её дополнительно в `Array.from`

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +                <p className="text text_type_main-medium">Перенеси ингредиенты сюда, чтобы&nbsp;собрать&nbsp;бургер</p>
🟡 **Можно улучшить:**

С пользователями рекомендуется придерживаться вежливого стиля речи на Вы, поэтому лучше заменить "перенеси" -> "перенесите"

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +                    handleClose={() => deleteHandler(item)}
🟡 **Можно улучшить:**

Вместо дополнительной инлайновой функции можно напрямую в компоненте вызывать функцию `handleClose(item)`, так как `item` мы тоже передаем. Таким образом мы избежим создания промежуточных функций и сэкономим ресурсы.

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +
🟡 **Можно улучшить:**

Пустые строки следует убирать, чтобы поддерживать форматирование кода

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +                filling.map((item, index) => item.count > 0 && (
🔴 **Нужно исправить:**

В массив `filling` уже должны попадать значение минимум в количестве равном 1, поэтому проводить дополнительную проверку нецелесообразно

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
>  // BurgerConstructor.propTypes = {
🔴 **Нужно исправить:**

Неиспользуемые или устаревшие PropTypes следует удалять из файлов, при необходимости его можно будет восстановить через историю в Git. Аналогично обратите внимание и в других компонентах.

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-filling/burger-filling.jsx
> +            isLocked={false}
🟡 **Можно улучшить:**

Если тип пропса = boolean и его значение = false, то можно его просто не указывать и удалить данную строку кода, эффект будет аналогичный текущему виду

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-filling/burger-filling.jsx
> +            handleClose={() => handleClose()}
🔴 **Нужно исправить:**

В текущей реализации следует удалить промежуточную стрелочную функцию, так как можно просто передать метод handleClose напрямую и не тратить дополнительные ресурсы на создания новых функций. В предложенной в рамках `BurgerConstructor` - добавить вызов `handleClose` c параметром `item`

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-ingredient/burger-ingredient.jsx
>      const openModal = () => {
🔴 **Нужно исправить:**

Функции открытия и закрытия создаюся сейчас для каждого элемента "ингредиент", поэтому чем больше у вас будет ингредиентов - тем больше будет создана функций и тем больше вы будете расходовать ресурсы браузера. Поэтому, учитывая что логика не отличается от элемента к элементу будет целесообразно вынести её в родительский компонент и передавать сюда через пропсы, обратно вызывая со значениеми конкретного ингредиента

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-ingredient/burger-ingredient.jsx
> +            {isModalOpen && (
🔴 **Нужно исправить:**

Описанное выше характерно и для этого случая, модальное окно следует сделать единственным экземпляром

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-ingredient/burger-ingredient.jsx
> +    filling && filling.map((el) => (el._id === props._id ? (count = el.count) : null));
🔴 **Нужно исправить:**

Предложенное вами вычисление значение `count` осуществляется через функцию `map`, что нецелесообразно, т.к. результатом действия не является массив данных, а единственное значение (функцию `map` необходимо применять только в случаях, когда мы хотим преобразовать один массив в другой на основе определенных правил). В данном случае вам следует воспользоваться функцией `find` или `findLast`, благодаря который вы сможете найти нужный элемент в массиве и определить значение его параметра `count`, если он там присутствует.

🟡 **Можно улучшить:**

Однако, такое вычисление предполагает в худшем случае полный проход по массиву, и так для каждого ингредиента, следовательно трудозатраты растут с увеличением кол-ва элементов. Поэтому, стоит обеспечить вычисление счетчиков в родительском компоненте за один проход по массиву, а сюда передавать уже готовое значение через пропс

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-ingredient/burger-ingredient.jsx
> +    let bunValue = bun && bun._id === props._id && bun.count;
🔴 **Нужно исправить:**

1) Значение `bunValue` не изменяется в других местах, поэтому его следует объявить как константу;

2) Кол-во булок добавляемых в бургер равно либо 0, либо 2, в вашем случае сейчас отображается 1

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
>      });
🔴 **Нужно исправить:**

Функция `scroll` не используется в рамках данного компонента, возможно она устарела, поэтому её следует убрать, как неиспользуемый код

2022-09-14 21:12 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const handleScroll = () => {
🟢 **Отлично:**

Вы успешно реализовали логику автоматического выбора таба самостоятельно, это полезный опыт

🟡 **Можно улучшить:**

Рекомендую обратить внимание на вспомогательную библиотеку `react-intersection-observer`. Разработчикам полезно использовать готовые решения, если они проверены временем, чтобы сэкономить время на другие полезные дела :)

2022-09-14 21:12 UTC, randomroot commented on src/services/actions/index.js
> +
🟡 **Можно улучшить:**

Рекомендуется стандартизировать объекты, передаваемые в `dispatch` в ваших функциях. Согласно общепринятым стандартам должен передаваться объект `{ type: string, payload?: any }`, где в `payload` кладутся все необходимые данные для работы редьюсера, если они нужны, в ином случае только `{ type }`

2022-09-14 21:12 UTC, randomroot commented on src/services/actions/index.js
> +                    bun: {},
🟡 **Можно улучшить:**

Значения `bun` и `filling` можно прописывать напрямую в редьюсере, т.к. они не зависят от данных полученных из API

2022-09-14 21:12 UTC, randomroot commented on src/services/actions/index.js
> +                item: item,
🟡 **Можно улучшить:**

В рамках стандарта ES6, если значение ключа совпадает с названием переменной, то его можно не дублировать, а просто оставить `{..., item, ...}`

2022-09-14 21:12 UTC, randomroot commented on src/services/reducers/index.js
> +                constructorData: {
🟡 **Можно улучшить:**

При получении списка ингредиентов вы скорее всего будете обнулять значение в конструкторе, поэтому можно упростить данный объект

2022-09-14 21:12 UTC, randomroot commented on src/services/actions/index.js
> +                    type: GET_INGREDIENTS_FAILED
🟡 **Можно улучшить:**

Рекомендуется передавать значения ошибки в стор, чтобы затем его залогирровать или отобразить пользователю сообщение с текстом данной ошибки (в чистом виде или переведенным на понятный обычному пользователю язык).
Аналогично для всех `_FAILED` результатов

2022-09-14 21:12 UTC, randomroot commented on src/services/reducers/index.js
> +                orderNumRequest: false,
🔴 **Нужно исправить:**

Если при выполнении запроса к API произошла ошибка, то содержимое хранилища соответствующего элемента следует приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично для списка ингредиентов.

2022-09-14 21:12 UTC, randomroot commented on src/services/reducers/index.js
> +            return {
🔴 **Нужно исправить:**

В `default` случае не требуется создавать копию значений стора, следует вернуть текущий объект

2022-09-14 21:12 UTC, randomroot commented on src/services/reducers/index.js
> +                image: action.payload.image,
🔴 **Нужно исправить:**

Нарушено форматирование кода, вложенные элементы должны иметь отступ, относительно родительского

2022-09-14 21:12 UTC, randomroot commented on src/services/reducers/index.js
> +                currentIngredientDetails: {
🟡 **Можно улучшить:**

Проверьте, присутствует ли необходимость в прямом создании объекта для `currentIngredientDetails` поэлементно или достаточно передать значение `action.payload` напрямую

2022-09-14 21:12 UTC, randomroot commented on src/services/reducers/index.js
> +                currentIngredientDetails: {
🟢 **Отлично:**

Сброс состояния при закрытии модального окна поможет избежать отображения старых значений при его открытии 👍

2022-09-14 21:12 UTC, randomroot commented on src/services/reducers/index.js
> +export const mainReducer = (state = initialState, action) => {
🟡 **Можно улучшить:**

Вы используете большой объект для `state` со всеми ключами для каждого редьюсера, целесообразно разбить его на несколько небольших, соответствующих каждому из них, для экономии памяти и улучшению читабельности кода

2022-09-14 21:12 UTC, randomroot commented on src/services/reducers/index.js
> +        case GET_TOTALPRICE: {
🟡 **Можно улучшить:**

Название экшена подразумевает изъятие из стора значение, а судя по функционалу происходит наоборот запись, поэтому рекомендуется переименовать его из `GET_` в `SET_` - так вы наглядно покажете его смысл

2022-09-14 21:12 UTC, randomroot commented on src/services/reducers/index.js
> +                    bun: {...action.item, count: 1}
🔴 **Нужно исправить:**

Обратите внимание, что булок у нас две в бургере - сверху и снизу :)

2022-09-14 21:12 UTC, randomroot commented on src/services/reducers/index.js
> +                    .filter((item) => item.count > 0),
🟡 **Можно улучшить:**

Текущая реализация не является оптимальной, т.к. создаются 2 массива - один после `map`, другой после `filter`. Обратите внимание, что вы можете задать каждому элементу в конструкторе свой уникальный ID, помимо ID ингредиента и затем отфильтровать его за один проход. Либо производить удаление, согласно индексу элемента в массиве.

2022-09-14 21:12 UTC, randomroot commented on src/services/reducers/index.js
> +            let ingredientSum = state.constructorData.filling.filter(function(item){return item._id === action.item._id}).length + 1;
🔴 **Нужно исправить:**

1) Значение ingredientSum не изменяется в других местах, поэтому его следует объявить как константу;

2) Для подсчета суммы следует воспользоваться функцией `reduce`, вместо `filter`, чтобы не создавать новый массив, а всего одну числовую переменную;

2022-09-14 21:12 UTC, randomroot commented on src/services/reducers/index.js
> +                        ({...item, added: ingredientSum})),
🔴 **Нужно исправить:**

Значение `added` не используется в проекте, кроме как в этой строке кода, поэтому его назначение стоит под вопросом и предположительно подлежит удалению. Аналогично ниже

2022-09-14 21:12 UTC, randomroot commented on src/services/reducers/index.js
> +                        ...[{ ...action.item, added: 1, key: action.key, count: ingredientSum }],
🟡 **Можно улучшить:**

Хранить кол-во добавленных ингредиентов выбранного типа в каждом из его копий нецелесообразно, лучше проводить подсчет на лету в отдельной функции в нужном компоненте. Либо хранить значение в отдельном объекте, который отвечает именно за кол-во элементов с выбором по ключу = _id.

2022-09-15 09:35 UTC, Sobolefff commented on src/components/app/app.jsx
> +  const oneFetch = useRef(false);
в документации сказано без проверки стриктмод в 18 реакте в деве рендерит 2 раза, меня это напрягает.

2022-09-15 21:22 UTC, randomroot requested changes
В рамках данной итерации вами было успешно и оперативно проведено множество улучшений и исправлений, направленных на улучшение производительности 👍 

Однако, хотел бы обратить ваше внимание на логику показа модального окна с заказом: этот момент не является критичным, однако он может повлиять на общее восприятие пользователем вашего приложения. 

Причина по которой данный момент считаю "нужно исправить": в большинстве случае следует исключать лишние вызовы API, чтобы не было злоупотребления со стороны пользователей, в том числе и случайных вызовов, плюс, пустое окно заказа не несет в себе информативности о происходящем.

2022-09-15 21:22 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
>      setIsOrderDetailsOpened(true);
🔴 **Нужно исправить:**

Сейчас API вызывается и открывается пустое модальное окно, если не были выбраны ни булка, ни ингредиенты, нужно обеспечить проверку и, по желанию, уведомить пользователя об этом, перед выполнением этих команд на пустое значение orderData. Текущее поведение может ввести в заблуждение пользователя, плюс будет произведен лишний запрос на сервер, который вернет ошибку 400.

2022-09-15 21:22 UTC, randomroot commented on src/components/order-details/order-details.jsx
> +    order &&
🟡 **Можно улучшить:**

В момент когда заказ создается или произошла ошибка можно выводить пользователю соответствующее сообщение, чтобы избежать пустых окон

2022-09-15 21:22 UTC, randomroot commented on src/services/reducers/index.js
> +            // const ingredientSum = state.constructorData.filling.filter(function(item){return item._id === action.item._id}).length + 1;
🔴 **Нужно исправить:**

Следует удалить закомментированный код

2022-09-15 21:22 UTC, randomroot commented on src/utils/api.js
> +    return await fetch(`${apiConfig.baseURL}orders`, {
🟡 **Можно улучшить:**

Одновременное использование подходов async/await и Promise не целесообразно, рекомендуется выбрать один из них в рамках функции

2022-09-16 20:37 UTC, randomroot approved these changes
🟢 **Работа принята!**

Все необходимые исправление были оперативно выполнены, поздравляю вас с успешной сдачей работы и желаю дальнейших успехов в обучении! 🐈 


P.S.
Кроме вышеупомянутых комментариев, согласно которым можно улучшить ваш код, хотел бы обратить ваше внимание на отображение списка ингредиентов на разных разрешениях экрана с разным количеством элементов - присутствуют некритичные дефекты с отображением карточек не полностью.

2022-09-16 20:40 UTC, merged